In [ ]:
# Listing 10.10

# Connector importieren
import sys, mysql.connector

# Verbindung zum Datenbankserver erstellen
try:
    connection = mysql.connector.connect \
        (host = "localhost", user = "root", passwd = "")
except:
    print("Keine Verbindung zum Server")
    sys.exit(0)

# Execution-Objekt erzeugen
cursor = connection.cursor()

# Datenbank erzeugen
# cursor.execute("CREATE DATABASE IF NOT EXISTS firma")
cursor.execute("DROP DATABASE IF EXISTS firma")
cursor.execute("CREATE DATABASE firma")

connection.commit()

# Execution-Objekt schliessen
cursor.close()

# Verbindung schliessen
connection.close()

In [ ]:
# Listing 10.11

# Connector importieren
import sys, mysql.connector

# Verbindung zur Datenbank auf dem Datenbankserver erstellen
try:
    connection = mysql.connector.connect(host = "localhost", \
        user = "root", passwd = "", db = "firma")
except:
    print("Keine Verbindung zum Server")
    sys.exit(0)

9# Execution-Objekt erzeugen
cursor = connection.cursor()

# Tabelle erzeugen
cursor.execute("CREATE TABLE IF NOT EXISTS personen"
      "(name VARCHAR(30), vorname VARCHAR(25),"
      "personalnummer INT(11),"
      "gehalt DOUBLE, geburtstag DATE)"
      "ENGINE=MyISAM DEFAULT CHARSET=UTF8")
connection.commit()

# Primärschlüssel erzeugen
cursor.execute("ALTER TABLE personen"
    " ADD PRIMARY KEY (personalnummer)")
connection.commit()

# Execution-Objekt schliessen
cursor.close()

# Verbindung schliessen
connection.close()

In [ ]:
# Listing 10.12

# Connector importieren
import sys, mysql.connector

# Verbindung zur Datenbank auf dem Datenbankserver erstellen
connection = mysql.connector.connect(host = "localhost", \
    user = "root", passwd = "", db = "firma")

# Execution-Objekt erzeugen
cursor = connection.cursor()

# Datensatz erzeugen
sql = "INSERT INTO personen VALUES('Maier', " \
    "'Hans', 6714, 3500, '1962-03-15')"
cursor.execute(sql)
connection.commit()

# Datensatz erzeugen
sql = "INSERT INTO personen VALUES('Schmitz', " \
    "'Peter', 81343, 3750, '1958-04-12')"
cursor.execute(sql)
connection.commit()

# Datensatz erzeugen
sql = "INSERT INTO personen VALUES('Mertens', " \
    "'Julia', 2297, 3621.5, '1959-12-30')"
cursor.execute(sql)
connection.commit()

# Execution-Objekt schliessen
cursor.close()

# Verbindung schliessen
connection.close()

In [ ]:
# Listing 10.13

# Connector importieren
import sys, mysql.connector

# Verbindung zur Datenbank auf dem Datenbankserver erstellen
try:
    connection = mysql.connector.connect(host = "localhost", \
        user = "root", passwd = "", db = "firma")
except:
    print("Keine Verbindung zum Server")
    sys.exit(0)

# Execution-Objekt erzeugen
cursor = connection.cursor()

# Daten auslesen
cursor.execute("SELECT * FROM personen")
result = cursor.fetchall()

# Execution-Objekt schliessen
cursor.close()

# Verbindung schliessen
connection.close()

# Daten ausgeben
for data in result:
    print(str(data[0]) + ", " + str(data[1]) + ", " +
        str(data[2]) + ", " + str(data[3]) + ", " +
        str(data[4]))